### ISSUE TITLE
Refactor backend structure?

### ISSUE THREAD

**Issue by chrille0313** [David-Pixeln/Pubrundan_ProjektTDA367#33]
Currently, we have divided everything up into folders depending on its use case (eg. controllers under /controllers etc.). However, I feel like this makes it much harder to find what you are looking for if you are working on a specific entity of the backend model. I think another folder structure which instead divides all files based on what component/entity it belongs to makes much more sense (eg. UserController and UserModel under /user or /users). What are your thoughts?

**Comment by Marten-Granath** [comment]
In this course, we rigidly adhere to the MVC pattern. Using the same division in our file structure gives a good overview of how our each part of the application connects with all other parts. That said, I do agree that it comes at the cost of active use (searching). For simplicity, I would probably prefer to keep the current file structure, yet I am not against changing it if everyone else agrees.

**Comment by Marten-Granath** [comment]
Another option is to simply introduce folders within models, controllers etc.

**Comment by chrille0313** [comment]
> In this course, we rigidly adhere to the MVC pattern. Using the same division in our file structure gives a good overview of how our each part of the application connects with all other parts. That said, I do agree that it comes at the cost of active use (searching). For simplicity, I would probably prefer to keep the current file structure, yet I am not against changing it if everyone else agrees.

The issue I see with this argument is that the backend part of our project is divided up into layers that don't interact with each other. For example, having for example users and posts, using the current structure, they would be divided into:

/controllers/UserController
/controllers/PostController

/models/User
/models/Post

If we were to change to the suggested structure we would have:

/users/User
/users/UserController

/posts/Post
/posts/PostController

This new structure wouldn't change the perception of the MVC implementation. You still have models and controllers separated, the only difference is what they are grouped by. This creates a much greater cohesion regarding each entity. Since we also have a lot of layers to each entity (Controllers, Services, Models, Repositories, DTO's, Exceptions) it makes it hard to get a grasp of the "scope"/"implemented components" of them. I would also argue that the "focus" of our backend/model lies on all the individual entities and not on the components/implementation around them. Thus, I believe our project structure should reflect/communicate this instead (if I open the project, I want to see which entities exist and not what components our api implementation make us of.

> Another option is to simply introduce folders within models, controllers etc.

I don't think this would solve the issue, it would only add an extra unnecessary layer (/controllers/UserController -> /controllers/User/UserController). Please correct me if my understanding is mistaken

**Comment by erikpersson0884** [comment]
At today's meeting we discussed the issue and decided to refactor the backend folder structure according to the proposal made earlier in this thread

**Comment by Marten-Granath** [comment]
For context, it quickly became apparent that we would introduce several new classes moving forward. Something which would make our current file structure messy. Thus, we decided to refactor the code as proposed above.
