### ISSUE TITLE
Refactor controller mappings

### ISSUE THREAD

**Issue by chrille0313** [David-Pixeln/Pubrundan_ProjektTDA367#34]
Currently, almost all controllers are using an absolute path for the api request mapping.
![image](https://github.com/David-Pixeln/Pubrundan_ProjektTDA367/assets/47303717/ea8f95e4-afff-473c-b4f5-cf5b601c2248)

This is bad practice and they should instead use a relative api path from the application config file.
![image](https://github.com/David-Pixeln/Pubrundan_ProjektTDA367/assets/47303717/b84ba1e3-16e1-4b8e-81e0-ac00bbffb98b)

**Comment by Marten-Granath** [comment]
Corrected and Closed.
